Resources:
  Mys3bucket:
    Type: AWS::S3::Bucket

Outputs:                        # this output value is retrieved by parent stack.
  s3ArnName:
    Description: It displays the output values
    Value: !GetAtt Mys3bucket.Arn

Transform:
 - macroname